Setting up css for the desktop version
WildCodeSchool-2023-09/JS-RemoteFR-jurascripts-P3-Geocode pull request #19
Opened 2023-12-27 18:02 UTC by Dricks45

2023-12-27 18:03 UTC, Vexen04 approved these changes

2023-12-28 02:43 UTC, blackstars64 approved these changes

2023-12-28 02:47 UTC, blackstars64 requested changes
ca ne passe pas au déploiement d'après le test  donc voir si on peux importé les image un peux comme dans un jsx sinon on voie ensemble après.

2023-12-28 13:53 UTC, blackstars64 approved these changes

2023-12-28 13:53 UTC, merged